# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDemo:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo(self):
        self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
        self.driver.set_window_size(1024, 576)
        self.driver.find_element(By.ID, "my-text-id").click()
        self.driver.find_element(By.ID, "my-text-id").send_keys("chuchu")
        self.driver.find_element(By.NAME, "my-password").click()
        self.driver.find_element(By.NAME, "my-password").send_keys("foo")
        self.driver.find_element(By.NAME, "my-textarea").click()
        self.driver.find_element(By.NAME, "my-textarea").send_keys("chuchu\\nfoo")
        dropdown = self.driver.find_element(By.NAME, "my-select")
        dropdown.find_element(By.XPATH, "//option[. = 'Two']").click()
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.NAME, "my-datalist").click()
        self.driver.find_element(By.NAME, "my-datalist").send_keys("Seattle")
        self.driver.find_element(By.ID, "my-check-1").click()
        self.driver.find_element(By.ID, "my-check-2").click()
        self.driver.find_element(By.ID, "my-radio-2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".container").click()
        self.driver.find_element(By.ID, "message").click()
        self.driver.find_element(By.ID, "message").click()
        assert self.driver.find_element(By.ID, "message").text == "Received!"
        self.driver.close()
