# -*- coding: utf-8 -*-
"""python-basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tK6vwjiE590_4KXEX3vXl3mBwiqluHAi

# Print
"""


def test_print():
    # Printar uma string
    print("Hello world!")


"""# Funções"""


# funcoes com parametros
def demo_func(x=0, y=0, z=0):
    return x + y + z


def test_function_with_parameter():
    print(demo_func(3, 5, 6))
    print(demo_func(1, 3, 5))
    print(demo_func(y=1))


"""Exercício
1. Crie uma função que recebe o valor 5, soma 2 a ele e retorna o resultado. Exiba o resultado
"""

# complete

"""# Loops"""


def test_loop_numbers():
    # for iterando numa lista de numeros
    numbers = [0, 1, 2, 3, 4, 5]
    for number in numbers:
        print(number)


def test_loop_strings():
    # for iterando numa lista de strings
    frutas = ["pera", "uva", "maçã"]
    for fruta in frutas:
        print(fruta)


"""# Condicionais"""


def test_conditonal_if():
    # condição com if
    a = 1
    b = 1
    if a == b:
        print("here")


def test_conditonal_if_else():
    # Condicao com if-else
    a = 1
    b = 2
    if a == b:
        print("here")
    else:
        print("there")


def test_conditonal_if_elif_else():
    # Condicao if-elif-else
    a = 1
    b = 2
    c = 3
    d = 4
    if a == b:
        print("here")
    elif a == c:
        print("there")
    elif a == d:
        print("somewhere")
    else:
        print("nowhere")


"""Exercícios
1. Exibir os numeros da lista [1,2,3,4,5,6,7,8,9,0] se for maior do que 3
2. Exibir as frutas da lista ["jaca", "morango", "tangerina", "maracuja"] se a fruta não for 'banana' ou 'jaca'

"""
lista1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
lista2 = ["jaca", "morango", "tangerina", "maracuja"]

# complete

"""# Classes e objetos"""


class Pessoa:
    nome = None
    idade = None
    naturalidade = None

    def andar(self, sentido):
        print(f"andou para {sentido}")

    def responder(self, pergunta):
        if "nome" in pergunta:
            print(self.nome)

        if "idade" in pergunta:
            print(self.idade)


def test_class():
    p = Pessoa()
    p.nome = "maria"
    p.idade = 23
    p.responder("qual o seu nome e idade?")


"""# Asserções"""


# asserções
def func(x, y, z):
    return x + y - z


def test_assert():
    assert func(1, 2, 3) == 0


"""# Decorator"""


def deco(func, *args):
    def inner(*args):
        print(f"antes da func '{func.__name__}'")
        r = func(*args)
        print(f"Resultado {r}")
        print(f"depois da func '{func.__name__}'")
        return r

    return inner


@deco
def func1(x, y):
    return x + y


def test_decorator():
    func1(1, 3)


"""# Exceptions"""


class CalculadoraFraca:
    def somar(self, *args):
        for n in args:
            n += n
        return n

    def subtrair(self, *args):
        raise NotImplementedError("Nao sei fazer isso ainda")

    def multiplicar(self, *args):
        raise NotImplementedError("Nao sei fazer isso ainda")

    def dividir(self, *args):
        raise NotImplementedError("Nao sei fazer isso ainda")


def test_exception():
    c = CalculadoraFraca()
    resultado = c.somar(1, 2)
    print(resultado)

    # Exceptions
    c.subtrair(1, 2, 3)


def test_try_except():
    # Try-except
    c = CalculadoraFraca()
    try:
        c.subtrair(6, 7, 8)
    except NotImplementedError as e:
        print(str(e))
