# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test(self):
        self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
        self.driver.set_window_size(1294, 741)
        self.driver.find_element(By.ID, "my-text-id").click()
        self.driver.find_element(By.ID, "my-text-id").send_keys("input")
        self.driver.find_element(By.NAME, "my-password").click()
        self.driver.find_element(By.NAME, "my-password").send_keys("password")
        self.driver.find_element(By.NAME, "my-textarea").click()
        self.driver.find_element(By.NAME, "my-textarea").send_keys(
            "textarea\\ntextarea2"
        )
        self.driver.find_element(By.NAME, "my-readonly").click()
        self.driver.find_element(By.NAME, "my-select").click()
        dropdown = self.driver.find_element(By.NAME, "my-select")
        dropdown.find_element(By.XPATH, "//option[. = 'Two']").click()
        self.driver.find_element(By.NAME, "my-datalist").click()
        self.driver.find_element(By.NAME, "my-datalist").send_keys("Seattle")
        self.driver.find_element(By.ID, "my-check-1").click()
        self.driver.find_element(By.ID, "my-check-2").click()
        self.driver.find_element(By.ID, "my-radio-2").click()
        self.driver.find_element(By.NAME, "my-date").click()
        self.driver.find_element(By.CSS_SELECTOR, ".old:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".active:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3)").click()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.NAME, "my-range").send_keys("2")
        self.driver.find_element(By.NAME, "my-range").click()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.NAME, "my-range")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.NAME, "my-range").send_keys("8")
        self.driver.find_element(By.NAME, "my-range").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".py-2").click()
        assert self.driver.find_element(By.ID, "message").text == "Received!"
