# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDemo:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.logout()
        self.driver.quit()

    def test_demo(self):
        self.negavegar()
        self.preencher_nome()
        self.preencher_senha()
        self.preencher_curriculo()
        self.selecionar_qtde_filhos()
        self.escolher_cidade_de_nescimento()
        self.escolher_musica_preferida()
        self.escolher_genero()
        self.submeter()
        relatorio_de_preechimento = self.reportar_preenchimento()
        assert relatorio_de_preechimento == "Received!"

    def logout(self):
        self.driver.close()

    def reportar_preenchimento(self):
        self.driver.find_element(By.CSS_SELECTOR, ".container").click()
        self.driver.find_element(By.ID, "message").click()
        self.driver.find_element(By.ID, "message").click()
        return self.driver.find_element(By.ID, "message").text

    def submeter(self):
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

    def escolher_genero(self):
        self.driver.find_element(By.ID, "my-radio-2").click()

    def escolher_musica_preferida(self):
        self.driver.find_element(By.ID, "my-check-1").click()
        self.driver.find_element(By.ID, "my-check-2").click()

    def escolher_cidade_de_nescimento(self):
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.NAME, "my-select")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.NAME, "my-datalist").click()
        self.driver.find_element(By.NAME, "my-datalist").send_keys("Seattle")

    def selecionar_qtde_filhos(self):
        dropdown = self.driver.find_element(By.NAME, "my-select")
        dropdown.find_element(By.XPATH, "//option[. = 'Two']").click()

    def preencher_curriculo(self):
        self.driver.find_element(By.NAME, "my-textarea").click()
        self.driver.find_element(By.NAME, "my-textarea").send_keys("chuchu\\nfoo")

    def preencher_senha(self):
        self.driver.find_element(By.NAME, "my-password").click()
        self.driver.find_element(By.NAME, "my-password").send_keys("foo")

    def preencher_nome(self):
        self.driver.find_element(By.ID, "my-text-id").click()
        self.driver.find_element(By.ID, "my-text-id").send_keys("chuchu")

    def negavegar(self):
        self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
        self.driver.set_window_size(1024, 576)
